### ISSUE TITLE
Support Hamcrest's matcher

### ISSUE THREAD

**Issue by flowersinthesand** [jhalterman/concurrentunit#10]
Hamcrest's matcher allows to write readable and typeable tests.
https://code.google.com/p/hamcrest/wiki/Tutorial

The following code snippet would be enough to implement this feature but I haven't tried it yet.

```java
public class Waiter {
    // ...
    public <T> void assertThat(T actual, org.hamcrest.Matcher<T> matcher) {
        try {
            org.hamcrest.MatcherAssert.assertThat("", actual, matcher);
        } catch (AssertionError e) {
            fail(e);
        }
    }
    // ...
}
```

When declaring a dependency for hamcrest, if you set its optional flag to true, you can still make concurrentunit zero-dependency. That means user should declare hamcrest dependency to use this feature.

```xml
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-all</artifactId>
    <version>1.3</version>
    <optional>true</optional>
</dependency>
```

This feature can reduce some assertion code by half.

```java
// Using assertTrue
threadAssertTrue(http.headerNames().containsAll(Arrays.asList("a", "b")) || http.headerNames().containsAll(Arrays.asList("A", "B")));

// Using assertThat
threadAssertThat(http.headerNames(), either(hasItems("a", "b")).or(hasItems("A", "B")));
```

What do you think? if you like it, I can work on a pull request.

**Comment by jhalterman** [comment]
That sounds good to me. Sure, send over a pull request!

**Comment by flowersinthesand** [comment]
FWIW, I think exposing waiter.assertThat in README would be attractive. Since most of users use Assert.assertXXX, they might feel that Waiter may not support such assertion types as I did.

Also, it can give users a hint that they should declare hamcrest to use such assertion through comment.

**Comment by jhalterman** [comment]
Done. Tnx!
