### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by rapgro** [jhalterman/concurrentunit#12]
Source files are missing license headers. Would you please contact upstream to fix it?
 https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
 concurrentunit-concurrentunit-0.4.2/src/main/java/net/jodah/concurrentunit/ConcurrentTestCase.java
 concurrentunit-concurrentunit-0.4.2/src/main/java/net/jodah/concurrentunit/Waiter.java
 concurrentunit-concurrentunit-0.4.2/src/main/java/net/jodah/concurrentunit/internal/ReentrantCircuit.java

From my point of view the Apache Software License 2.0 is fine, see
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#SoftwareLicenses
But it looks like that upstream has forgotten to add a header to the License in tarball.
See APPENDIX: How to apply the Apache License to your work
http://www.apache.org/licenses/LICENSE-2.0

Downstream package review:
https://bugzilla.redhat.com/show_bug.cgi?id=1305365

**Comment by jhalterman** [comment]
@rapgro To be clear, you just want the license header added to all of the .java files?

**Comment by jhalterman** [comment]
Let me know if there's something else you need with this.

**Comment by rapgro** [comment]
Okay, thanks. We'll re-review.
