### ISSUE TITLE
Await for a specific time unit always uses milliseconds

### ISSUE THREAD

**Issue by xaviarias** [jhalterman/concurrentunit#17]
Await for a specific time unit does not delegate to the waiter's appropriate method. Is that the expected behaviour?

https://github.com/jhalterman/concurrentunit/blob/c88779fec230189cd14724fc0217e20736e0d07d/src/main/java/net/jodah/concurrentunit/ConcurrentTestCase.java#L117

**Comment by jhalterman** [comment]
Fixed - thanks for mentioning.

**Comment by jhalterman** [comment]
Fixed in 0.4.3.
