### ISSUE TITLE
assertEquals parameters order

### ISSUE THREAD

**Issue by ufoscout** [jhalterman/concurrentunit#4]
Maybe this is not an issue but a desired behaviour, however, it seems to me that the order of the parameters in the assertEquals method is wrong:

public void assertEquals(Object actual, Object expected)

Being a long time user of JUnit, I expected the "actual" parameter to be in the second position instead of the first one.

**Comment by jhalterman** [comment]
The ordering was based on TestNG, which is what I typically use for unit testing, but since xUnit is more common I don't mind reversing the order.
